### ISSUE TITLE
Decorator pattern for Account

### ISSUE THREAD

**Issue by KacMac** [sorwat/bank#23]

**Comment by Ananas97** [comment]
overdraft (some can have the possibility)

**Comment by Ananas97** [comment]
https://fossies.org/linux/apache-groovy-docs/html/documentation/design-pattern-decorator.html

https://gist.github.com/sbrady/277dd678509061e35bf5

**Comment by Ananas97** [comment]
has been merged yesterday see branch AR-decorator
